ALTER TABLE users ADD COLUMN sync_mode TEXT NOT NULL DEFAULT 'weekday';
ALTER TABLE users ADD COLUMN sync_weekdays_mask INTEGER NOT NULL DEFAULT 1;
ALTER TABLE users ADD COLUMN sync_anchor_date TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN sync_interval_days INTEGER NOT NULL DEFAULT 7;
